name: Test OpenAPI generator

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v4.2.2

      - name: Setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run tests
        run: ./gradlew :app:test
